### ISSUE TITLE
Support installation in Jupyter notebooks

### ISSUE THREAD

**Issue by thewtex** [imagej/pyimagej#21]
For accessibility and reproducibility of Jupyter notebooks that use pyimagej, especially for examples, we want to support installation and execution via a conda-forge package. For example:

```
import sys
!conda install --yes --prefix {sys.prefix} -c conda-forge pyimagej

import imagej
ij = imagej.init()
```

To do this, two improvements appear to be required (see discussion in https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/issues/116):

1. Support picking up Java and pyjnius jars when environmental variables are not defined in standard system locations, e.g. where conda-forge packages install them.
2. Make import's and system initialization robust to avoid the error `ValueError: VM is already running, can't set options`

The following minimal notebook demonstrates the desired behavior and current error:

[PyimagejJupyterInstallation.ipynb.zip](https://github.com/imagej/pyimagej/files/2658399/PyimagejJupyterInstallation.ipynb.zip)

CC: @hadim @ctrueden

**Comment by ctrueden** [comment]
For (1), I was thinking something like this:

<details><summary>git diff</summary>

```diff
diff --git a/scyjava/__init__.py b/scyjava/__init__.py
index 6335759..657c324 100644
--- a/scyjava/__init__.py
+++ b/scyjava/__init__.py
@@ -1,5 +1,7 @@
 import logging
 import os
+import sys
+from pathlib import Path

 _logger = logging.getLogger(__name__)

@@ -15,14 +17,15 @@ def _init_jvm():

     PYJNIUS_JAR_STR = 'PYJNIUS_JAR'
     if PYJNIUS_JAR_STR not in globals():
+        PYJNIUS_JAR = None
         try:
-            PYJNIUS_JAR = os.environ[PYJNIUS_JAR_STR]
-            jnius_config.add_classpath(PYJNIUS_JAR)
+            PYJNIUS_JAR = Path(os.environ[PYJNIUS_JAR_STR])
         except KeyError as e:
-            if e.args[0] == PYJNIUS_JAR_STR:
-                _logger.error('Unable to import scyjava: %s environment variable not defined.', PYJNIUS_JAR_STR)
-            else:
-                raise e
+            PYJNIUS_JAR = Path(sys.prefix) / 'share/pyjnius/pyjnius.jar'
+        if PYJNIUS_JAR.is_file():
+            jnius_config.add_classpath(PYJNIUS_JAR)
+        else:
+            _logger.error('Unable to import scyjava: pyjnius JAR not found.')
             return None

     endpoints = scyjava_config.get_endpoints()
```

</details>

Although I haven't tested it yet. (And I confess I find the `if PYJNIUS_JAR_STR not in globals():` test suspicious since I do not understand its purpose.)

For (2): @hadim is this the issue fixed by conda-forge/pyimagej-feedstock#3? Or is that for something else? Do we need changes in pyimagej itself to address this?

**Comment by hadim** [comment]
Your diff looks ok to me.

About https://github.com/conda-forge/pyimagej-feedstock/pull/3, the issue was coming from the OpenJDK conda packages. It should be fixed in 1-2h.

So nothing to do on the pyimagej side but only on the recipe itself.

I'll ping you once everything s back to normal.

**Comment by hadim** [comment]
All good. I manually tested `conda create -n ij pyimagej` on Windows and Linux and it works fine.

**Comment by DaniBodor** [comment]
I am a bit lost by now on how to install pyimagej. I've been trying to follow the discussion above and [here](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/issues/116), but am still stuck with an error.
Any ideas what to do?

What I have done so far
in Conda prompt:
```
conda create -y -c conda-forge -n pyij pyimagej scikit-image
activate imagej
```

then in Spyder IDE:
```
import sys
!conda install --yes --prefix {sys.prefix} -c conda-forge pyimagej
import imagej
ij=imagej.init()
```

this resulted in the following error:
> INFO 2019-02-26 14:30:19,078: Failed to bootstrap the artifact.
> INFO 2019-02-26 14:30:19,078: 
> INFO 2019-02-26 14:30:19,078: Possible solutions:
> INFO 2019-02-26 14:30:19,078: * Double check the endpoint for correctness (https://search.maven.org/).
> INFO 2019-02-26 14:30:19,078: * Add needed repositories to ~/.jgorc [repositories] block (see README).
> INFO 2019-02-26 14:30:19,078: * Try with an explicit version number (release metadata might be wrong).
> 
> Traceback (most recent call last):
> 
>   File "<ipython-input-24-c619ba593a5e>", line 1, in <module>
>     ij=imagej.init()
> 
>   File "C:\Users\dani\Anaconda3\lib\site-packages\imagej\imagej.py", line 104, in init
>     import imglyb
> 
>   File "C:\Users\dani\Anaconda3\lib\site-packages\imglyb\__init__.py", line 41, in <module>
>     config, _ = _init_jvm_options()
> 
>   File "C:\Users\dani\Anaconda3\lib\site-packages\imglyb\__init__.py", line 36, in _init_jvm_options
>     import scyjava
> 
>   File "C:\Users\dani\Anaconda3\lib\site-packages\scyjava\__init__.py", line 55, in <module>
>     jnius = _init_jvm()
> 
>   File "C:\Users\dani\Anaconda3\lib\site-packages\scyjava\__init__.py", line 41, in _init_jvm
>     verbose=scyjava_config.get_verbose()
> 
>   File "C:\Users\dani\Anaconda3\lib\site-packages\jgo\jgo.py", line 457, in resolve_dependencies
>     raise e
> 
>   File "C:\Users\dani\Anaconda3\lib\site-packages\jgo\jgo.py", line 448, in resolve_dependencies
>     mvn_out = run_and_combine_outputs(mvn, *mvn_args)
> 
>   File "C:\Users\dani\Anaconda3\lib\site-packages\jgo\jgo.py", line 205, in run_and_combine_outputs
>     return subprocess.check_output((command,) + args, stderr=subprocess.STDOUT)
> 
>   File "C:\Users\dani\Anaconda3\lib\subprocess.py", line 336, in check_output
>     **kwargs).stdout
> 
>   File "C:\Users\dani\Anaconda3\lib\subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> 
> CalledProcessError: Command '('C:\\Users\\dani\\Anaconda3\\Library\\bin\\mvn.CMD', '-B', '-f', 'C:\\Users\\dani\\.jgo\\net\\imglib\\imglib2-imglyb\\0.3.0+net.imagej-imagej-RELEASE+net.imagej-imagej-RELEASE+net.imglib-imglib2-imglyb-0.3.0+net.imglib-imglib2-imglyb-0.3.0+net.imglib-imglib2-imglyb-0.3.0+net.imglib-imglib2-imglyb-0.3.0\\pom.xml', 'dependency:resolve')' returned non-zero exit status 1.

**Comment by imagejan** [comment]
> `conda create -y -c conda-forge -n pyij pyimagej scikit-image`
`activate imagej`

Why did you create a conda environment with the name "pyij", but then activate the environment with the name "imagej"? Does the second line succeed? If yes, how did you create the `imagej` environment?

**Comment by DaniBodor** [comment]
it did succeed. 
I did this because on a previous try it got stuck and I restarted conda prompt. if i would try `conda create -y -c conda-forge -n imagej pyimagej scikit-image` I get the error message  `CondaValueError: prefix already exists: C:\Users\dani\Anaconda3\envs\imagej`

`conda clean --all -y` did not solve that error, so I decided to give it a new name, as I didn't know how to remove the environment

**Comment by DaniBodor** [comment]
OK, so I've deleted the original imagej environment and reinstalled it with `conda create -y -c conda-forge -n pyij pyimagej scikit-image` (I assume this would be equivalent to activating pyij, but decided to go this way to have everything as close to the instructions here as possible).

following the same steps as above, I now get a different error:

```
ij=imagej.init()
ERROR 2019-02-26 15:00:36,307: Unable to import scyjava: PYJNIUS_JAR environment variable not defined.
Traceback (most recent call last):

  File "<ipython-input-4-c619ba593a5e>", line 1, in <module>
    ij=imagej.init()

  File "C:\Users\dani\Anaconda3\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb

  File "C:\Users\dani\Anaconda3\lib\site-packages\imglyb\__init__.py", line 41, in <module>
    config, _ = _init_jvm_options()

  File "C:\Users\dani\Anaconda3\lib\site-packages\imglyb\__init__.py", line 36, in _init_jvm_options
    import scyjava

  File "C:\Users\dani\Anaconda3\lib\site-packages\scyjava\__init__.py", line 57, in <module>
    raise ImportError('Unable to import scyjava dependency jnius.')

ImportError: Unable to import scyjava dependency jnius.
```

**Comment by ctrueden** [comment]
@DaniBodor A couple of important basic things to understand:

1. As @imagejan points out, the commands you cited above are a bit mixed up. Be sure you are _creating an environment with a particular name_ and then _activating the environment with that same name_. If you get an error about how an environment with a particular name already exists, just delete it first using `conda env remove -n imagej` before recreating it.

2. Activating a conda environment in a terminal activates it _only within that terminal_. If you switch over to Spyder IDE launched from outside that particular terminal, you will _not_ be inside the same activate conda environment.

3. The hack that you are trying to use from Spyder—`!conda install --yes --prefix {sys.prefix} -c conda-forge pyimage`—specifically _does not work_ right now, as documented by this issue. So this approach will not yield success for you until we iron it out.

From some quick web searches, it seems like you can: A) create the conda environment; B) activate the environment; then C) launch `spyder` _from that same terminal while environment is active_ in order to benefit from the environment within Spyder. See [here](https://stackoverflow.com/a/30170469/1207769). You may also want to read [the relevant docs from Spyder](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder) about this stuff. Note that I have never used Spyder personally.

**Comment by ctrueden** [comment]
An update on this issue!

I believe that with the release of scyjava 0.2.2, the conda environment does not need to be explicitly activated anymore, since the environment variable values will be autodetected.

However, there is currently an issue with conda-forge, so the new scyjava release has not propagated to conda yet. But in the meantime, it can be installed from pip via `!pip install scijava==0.2.2` after the `!conda` line.

**Comment by ctrueden** [comment]
The scyjava 0.2.2 release is now on conda-forge.

With that, I believe this issue is fully resolved. It is now possible to hack an existing `sys.prefix` using conda from the notebook, with a leading cell like:
```
import sys
!conda install --yes --prefix {sys.prefix} -c conda-forge pyimagej
```
Or if you want OpenJDK 8 (which is what we test ImageJ against most thoroughly):
```
import sys
!conda install --yes --prefix {sys.prefix} -c conda-forge pyimagej openjdk=8
```
And then in subsequent cell do:
```
import imagej
ij = imagej.init()
```
Or whatever usual pyimagej stuff you want to do.

At least, it works on my system starting from a simple conda environment created by:
```
conda create -n dev jupyter
/usr/local/miniconda3/envs/dev/bin/jupyter notebook
```
I.e.: _Without_ explicitly activating the new environment. 💪

Please give it a try and comment here how it's working (or not) for you!

**Comment by thewtex** [comment]
@ctrueden awesome!

**Comment by ctrueden** [comment]
With 31fe70b9f51c9b9cf7bb96381906697d7b56a1b6, there is now a note in the README documenting the "install from inside a Jupyter notebook" hack.
